version: '2.0'
services:
  #react project
  react-project:
    build: ./react-project
    image: react-project
    container_name: fontend
    ports:
      - "5173:5173"
    environment:
      - API_URL=http://proxy:4000
    depends_on: 
      - proxy


  # Reverse proxy server
  proxy:
    build: ./proxy-server
    image: proxy-server
    container_name: proxy4
    ports:
      - "4000:4000"
    environment:
      - FWD_URL=http://app:3000
    depends_on:
      - app

  #Node server
  app:
    build: ./node-server
    container_name: backend-app
    environment:
      - MONGODB_URL=mongodb://mongo
      - MONGODB_PORT=27017
      - JWT_SECRET=12345678
    depends_on:
      - mongo

  #MongoDb service
  mongo:
    image: mongo:latest
    container_name: mongodb2
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data: 
    driver: local